/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.ImageIcon;
import poker.JugadorRegistrado;

/**
 *Ventana para elegir el modo de juego
 * @author Alvaro de las Heras
 */
public class Modo extends javax.swing.JFrame {
    
    private String tipo;
    private JugadorRegistrado jug;
    private boolean mesa;

    public Modo(JugadorRegistrado jug) {
        initComponents();
        this.jug=jug;
        //Deja seleccionado el boton
        rbtnIndividual.setSelected(true);
        //Anagrama
        lblAnagrama.setSize(60,60);
        ImageIcon imagen2 = new ImageIcon("Anagrama.png");
        ImageIcon imgRedimensionada2 = new ImageIcon(imagen2.getImage().getScaledInstance(lblAnagrama.getWidth(), lblAnagrama.getHeight(), 1));
        lblAnagrama.setIcon(imgRedimensionada2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modo = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblAnagrama = new javax.swing.JLabel();
        rbtnMesa = new javax.swing.JRadioButton();
        rbtnIndividual = new javax.swing.JRadioButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modo");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Elegantlight", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(lblAnagrama, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAnagrama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        modo.add(rbtnMesa);
        rbtnMesa.setFont(new java.awt.Font("Open Sans Light", 0, 18)); // NOI18N
        rbtnMesa.setText("Mesa");
        rbtnMesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnMesaMouseClicked(evt);
            }
        });
        rbtnMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMesaActionPerformed(evt);
            }
        });

        modo.add(rbtnIndividual);
        rbtnIndividual.setFont(new java.awt.Font("Open Sans Light", 0, 18)); // NOI18N
        rbtnIndividual.setText("Individual");
        rbtnIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnIndividualMouseClicked(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Open Sans Light", 0, 18)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnIndividual)
                    .addComponent(rbtnMesa)
                    .addComponent(btnAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtnMesa)
                .addGap(18, 18, 18)
                .addComponent(rbtnIndividual)
                .addGap(21, 21, 21)
                .addComponent(btnAceptar)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(311, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //Lleva a la siguiente ventana segun la opcion que elija el usuario
        if (mesa){
            this.setVisible(false);
            Mesa frame= new Mesa(jug,"Mesa");
            frame.setVisible(true);
        }
        else {
            this.setVisible(false);
            Individual frame= new Individual(jug,"Individual");
            frame.setVisible(true);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void rbtnMesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnMesaMouseClicked
        //Activa el modo de mesa
        mesa=true;
    }//GEN-LAST:event_rbtnMesaMouseClicked

    private void rbtnIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnIndividualMouseClicked
        //Activa el modo individual 
        mesa=false;
    }//GEN-LAST:event_rbtnIndividualMouseClicked

    private void rbtnMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMesaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAnagrama;
    public static javax.swing.ButtonGroup modo;
    private javax.swing.JRadioButton rbtnIndividual;
    private javax.swing.JRadioButton rbtnMesa;
    // End of variables declaration//GEN-END:variables
}
