/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio_2;

/**
 *
 * @author Alvaro
 */
public class Interfaz extends javax.swing.JFrame {
    //Declaramos el buffer
    private Buffer buf;
    
    public Interfaz() {
        initComponents();
        
        
        buf = new Buffer(buffer);
        //Creamos todos los objetos requeridos
        Productor p= new Productor(buf,100,'A');
        Productor p1= new Productor(buf,100,'B');
        Productor p2= new Productor(buf,100,'C');
        Productor p3= new Productor(buf,100,'D');
        Productor p4= new Productor(buf,100,'E');
        Consumidor c= new Consumidor(buf,"Maria");
        Consumidor c1= new Consumidor(buf,"Juan");
        Consumidor c2= new Consumidor(buf,"Luis"); 
        //Se inician todos los hilos
        p.start();
        p1.start();
        p2.start();
        p3.start();
        p4.start();
        c.start();
        c1.start();
        c2.start();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buffer = new javax.swing.JTextField();
        paraProd = new javax.swing.JButton();
        paraCons = new javax.swing.JButton();
        reanudaCons = new javax.swing.JButton();
        ReanudaProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contenido del buffer: ");

        buffer.setEditable(false);
        buffer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bufferActionPerformed(evt);
            }
        });

        paraProd.setText("Detener productores");
        paraProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraProdActionPerformed(evt);
            }
        });

        paraCons.setText("Detener consumidores");
        paraCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraConsActionPerformed(evt);
            }
        });

        reanudaCons.setText("Reanudar consumidores");
        reanudaCons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reanudaConsActionPerformed(evt);
            }
        });

        ReanudaProd.setText("Reanudar productores");
        ReanudaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReanudaProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paraProd)
                            .addComponent(paraCons))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ReanudaProd)
                            .addComponent(reanudaCons))
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(buffer)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(buffer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paraProd)
                    .addComponent(ReanudaProd))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reanudaCons)
                    .addComponent(paraCons))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bufferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bufferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bufferActionPerformed

    private void paraProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraProdActionPerformed
        //Bloquea la clase paso
        buf.getPasoProd().cerrar();   
    }//GEN-LAST:event_paraProdActionPerformed

    private void ReanudaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReanudaProdActionPerformed
        //Desbloquea la clase paso
        buf.getPasoProd().abrir();
    }//GEN-LAST:event_ReanudaProdActionPerformed

    private void paraConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraConsActionPerformed
        //Bloquea la clase paso
        buf.getPasoCons().cerrar();      
    }//GEN-LAST:event_paraConsActionPerformed

    private void reanudaConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reanudaConsActionPerformed
        //Desbloquea la clase paso
        buf.getPasoCons().abrir();
    }//GEN-LAST:event_reanudaConsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ReanudaProd;
    private javax.swing.JTextField buffer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton paraCons;
    private javax.swing.JButton paraProd;
    private javax.swing.JButton reanudaCons;
    // End of variables declaration//GEN-END:variables
}
